
import { InterviewSession, Answer } from "@/types";
import { jsPDF } from "jspdf";
import autoTable from 'jspdf-autotable';

export const generatePDF = (interview: InterviewSession): void => {
  const doc = new jsPDF();

  // Add title
  doc.setFontSize(20);
  doc.setTextColor(124, 58, 237); // VidyaMitra purple
  doc.text("VidyaMitra Interview Report", 20, 20);

  // Add subtitle with date
  doc.setFontSize(12);
  doc.setTextColor(100, 100, 100);
  const formattedDate = new Date(interview.date).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });
  doc.text(`${interview.roleName} Interview | ${formattedDate}`, 20, 30);

  // Check if interview was aborted
  if (interview.aborted) {
    // Add aborted warning with large red text
    doc.setFontSize(24);
    doc.setTextColor(255, 0, 0); // Red color
    doc.setFont("helvetica", "bold");
    doc.text("🚫 INTERVIEW ABORTED", 20, 45);

    doc.setFontSize(14);
    doc.text(`Reason: ${interview.abortReason || "Possible malpractice detected"}`, 20, 55);

    doc.setFontSize(12);
    doc.setTextColor(44, 62, 80);
    doc.setFont("helvetica", "normal");
    doc.text("This interview was terminated due to possible malpractice.", 20, 65);
    doc.text("Examples include: tab switching, early exit, or other suspicious activities.", 20, 75);

    // Save PDF with aborted indicator
    const fileName = `VidyaMitra_${interview.roleName.replace(/[^a-zA-Z0-9 -]/g, '')}_ABORTED_${formattedDate.replace(/\s/g, '_')}.pdf`;
    const blob = doc.output('blob');
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = fileName;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    return;
  }

  // Continue with normal report for non-aborted interviews

  // Add overall score
  doc.setFontSize(16);
  doc.setTextColor(44, 62, 80);
  doc.text("Overall Performance", 20, 45);

  doc.setFontSize(14);
  doc.setTextColor(41, 128, 185);
  doc.text(`Score: ${interview.score?.toFixed(1)}/10`, 20, 55);

  // Add feedback
  doc.setFontSize(12);
  doc.setTextColor(44, 62, 80);

  const feedback = interview.feedback || "No feedback available";
  const feedbackLines = doc.splitTextToSize(feedback, 170);
  doc.text(feedbackLines, 20, 65);

  // Add questions and answers table
  doc.setFontSize(16);
  doc.setTextColor(44, 62, 80);
  doc.text("Questions & Answers", 20, 90);

  const tableRows: any[] = [];

  interview.questions.forEach((question, index) => {
    const answer = interview.answers.find(a => a.questionId === question.id);

    if (answer) {
      tableRows.push([
        (index + 1).toString(),
        question.text,
        answer.text,
        answer.feedback ? answer.feedback.overall.toFixed(1) + "/10" : "N/A"
      ]);
    } else {
      tableRows.push([
        (index + 1).toString(),
        question.text,
        "No answer provided",
        "N/A"
      ]);
    }
  });

  autoTable(doc, {
    startY: 95,
    head: [['#', 'Question', 'Your Answer', 'Score']],
    body: tableRows,
    headStyles: {
      fillColor: [41, 128, 185],
      textColor: [255, 255, 255],
      fontStyle: 'bold'
    },
    columnStyles: {
      0: { cellWidth: 10 },
      1: { cellWidth: 60 },
      2: { cellWidth: 80 },
      3: { cellWidth: 20 }
    },
    styles: {
      overflow: 'linebreak',
      cellPadding: 4,
    },
    theme: 'striped'
  });

  // Add improvement suggestions
  let yPosition = (doc as any).lastAutoTable.finalY + 20;

  doc.setFontSize(16);
  doc.setTextColor(44, 62, 80);
  doc.text("Areas for Improvement", 20, yPosition);

  yPosition += 10;
  doc.setFontSize(12);

  // Collect all suggestions
  const allSuggestions: string[] = [];
  interview.answers.forEach(answer => {
    if (answer.feedback && answer.feedback.suggestions) {
      answer.feedback.suggestions.forEach(suggestion => {
        if (!allSuggestions.includes(suggestion)) {
          allSuggestions.push(suggestion);
        }
      });
    }
  });

  if (allSuggestions.length > 0) {
    allSuggestions.forEach((suggestion, index) => {
      yPosition += 8;
      doc.text(`${index + 1}. ${suggestion}`, 25, yPosition);
    });
  } else {
    yPosition += 8;
    doc.text("No specific improvement suggestions.", 25, yPosition);
  }

  // Add footer
  yPosition = doc.internal.pageSize.height - 20;
  doc.setFontSize(10);
  doc.setTextColor(150, 150, 150);
  doc.text("Generated by VidyaMitra - AI Career Companion", 20, yPosition);

  // Save PDF
  const fileName = `VidyaMitra_${interview.roleName.replace(/[^a-zA-Z0-9 -]/g, '')}_Interview_${formattedDate.replace(/\s/g, '_')}.pdf`;
  const blob = doc.output('blob');
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = fileName;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};
